'''
Constants used for the rest of the scripts
'''


# data directories from root
DATA_RAW_DIR = 'data/raw/'
DATA_PROCESSING_DIR = 'data/processing/'
DATA_CELAN_DIR = 'data/clean/'

ACCIDENT_MAIN_DIR = 'ACCIDENT/'

ACCIDENT_DATA_GENERAL_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ACCIDENT.csv'
ACCIDENT_DATA_NODE_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'NODE.csv'
ACCIDENT_DATA_GENERAL_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ACCIDENT.csv'
ACCIDENT_DATA_GENERAL_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ACCIDENT.csv'
ACCIDENT_DATA_GENERAL_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ACCIDENT.csv'