'''
Constants used for the rest of the scripts
'''


# data directories from root
DATA_RAW_DIR = 'data/raw/'
DATA_CELAN_DIR = 'data/clean/'

ACCIDENT_MAIN_DIR = 'ACCIDENT/'

ACCIDENT_DATA_GENERAL_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ACCIDENT.csv'
ACCIDENT_DATA_NODE_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'NODE.csv'
ACCIDENT_DATA_PERSON_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'PERSON.csv'
ACCIDENT_DATA_ATMOSPHERIC_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ATMOSPHERIC_COND.csv'
ACCIDENT_DATA_ROAD_COND_DIR = DATA_RAW_DIR + ACCIDENT_MAIN_DIR + 'ROAD_SURFACE_COND.csv'

PROCESSED_DATA_DIR = DATA_CELAN_DIR + 'processed.csv'


EARLIEST_DATE = '2019/01/01'